name: Main

on: 
  schedule:
    - cron:  '0 18 * * *'
  release:
    types: [published, prereleased]


env:
    
  AWS_ACCESS_KEY_DEPLOYMENT: "${{ secrets.AWS_ACCESS_KEY_DEPLOYMENT }}"
  AWS_SECRET_KEY_DEPLOYMENT: "${{ secrets.AWS_SECRET_KEY_DEPLOYMENT }}"
  MAVEN_SERVER_PASSWORD: "${{ secrets.MAVEN_SERVER_PASSWORD }}"
  RACKSPACE_USER: "${{ secrets.RACKSPACE_USER }}"
  RACKSPACE_PASSWORD: "${{ secrets.RACKSPACE_PASSWORD }}"
  VERSION_CYBERDUCK_IO_HOST_NAME: "${{ secrets.VERSION_CYBERDUCK_IO_HOST_NAME }}"
  VERSION_CYBERDUCK_IO_KNOW_HOSTS: "${{ secrets.VERSION_CYBERDUCK_IO_KNOW_HOSTS }}"
  VERSION_CYBERDUCK_IO_USER: "${{ secrets.VERSION_CYBERDUCK_IO_USER }}"

jobs:
  get_variables_job:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS_WIN: " "
      MAVEN_ARGS_MACOS: " "
      AWS_PATH: " "
      RACKSPACE_PATH:  " "
      FILETRANSFER_PATH_MACOS: " "
      FILETRANSFER_PATH_WIN: " "
      BRANCH_TAG: " "
      PUBLISH_TIGGER: false
      variable2:  ""
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables if schedule
        id: set_vars_schedule
      
        run: echo github.event_name 
      
      